version: '3'

silent: true

includes:
  # npm:
  #   taskfile: ./Frontend/Taskfile.yml
  #   dir: ./Frontend

  nuke:
     taskfile: ./build/Taskfile.yml

tasks:
  default:
    cmds:
      - task --list-all

  net:build:
    cmds:
      - dotnet clean
      - dotnet build

  net:test:
    cmds:
      - dotnet test